<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BuildingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('buildings')->insert([
            [
                'name' => 'Gedung A atau Gedung Susilo Bambang Yudhoyono',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Gedung A adalah salah satu fasilitas utama di UIN Maulana Malik Ibrahim Malang Kampus 2. Gedung ini digunakan untuk berbagai kegiatan akademik dan administrasi, termasuk ruang kelas dan kantor administrasi.',
                'opening_hours' => 'Senin - Jumat: 08.00 - 20.30, Sabtu - Minggu: Tutup',
                'floors' => 4,
                'rooms_per_floor' => 'Lantai 1: Ruang Direktur, Ruang Rapat, Ruang Administrasi, Ruang Keuangan, Lounge; Lantai 2: Ruang Kaprodi, Ruang Sekretaris Prodi; Lantai 3: Ruang Kuliah, Ruang Rapat, Ruang Prof. Dr. Imam Suprayogo; Lantai 4: Library',
                'area' => 1500.0,
                'latitude' => -7.906198459962819,
                'longitude' => 112.5781599950464,
                'additional_facilities' => 'Wi-Fi gratis, Area parkir VIP',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/gedungA.jpg',
            ],
            [
                'name' => 'Administrasi Rumah Singgah',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Administrasi Rumah Singgah adalah pusat administrasi yang bertanggung jawab atas pengelolaan dan pelayanan terkait dengan rumah singgah di wilayah kampus UIN Malang Kampus 2.',
                'opening_hours' => 'Senin - Minggu: 24 Jam',
                'floors' => 4,
                'rooms_per_floor' => 'Lantai 1: Lobby, Cafetaria, Reception, Guest Room no 101-104; Lantai 2: Guest Room; Lantai 3: Meeting Room; Lantai 4: Hall Utama',
                'area' => 1500.0,
                'latitude' => -7.906198459962819,
                'longitude' => 112.5781599950464,
                'additional_facilities' => 'Wi-Fi gratis, Area parkir VIP',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/rumahsinggah.jpg',
            ],
            [
                'name' => 'Gedung B atau Gedung Susilo Bambang Yudhoyono (FKIK)',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Gedung B adalah salah satu fasilitas utama di Fakultas Kedokteran dan Ilmu Kesehatan (FKIK) yang digunakan untuk perkuliahan dan berbagai kegiatan akademik.',
                'opening_hours' => 'Senin - Jumat: 08.00 - 20.30, Sabtu - Minggu: Tutup',
                'floors' => 4,
                'rooms_per_floor' => 'Lantai 1: Ruang Kuliah 301 - 302, Ruang Resepsionis; Lantai 2: Ruang Kuliah 303 - 305; Lantai 3: Ruang Kuliah 306 - 307; Lantai 4: Auditorium',
                'area' => 1050.0,
                'latitude' => -7.90631699575982,
                'longitude' => 112.57868840306934,
                'additional_facilities' => 'Wi-Fi gratis, Area parkir',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/gedungB.jpg',
            ],
            [
                'name' => 'PSSF (Gedung Asrama Mahasiswa/i Farmasi)',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'PSSF adalah fasilitas hunian yang disediakan khusus untuk mahasiswa dan mahasiswi jurusan Farmasi. Asrama ini dirancang untuk memberikan lingkungan yang nyaman dan mendukung kegiatan akademik.',
                'opening_hours' => 'Senin - Minggu: 04.00 - 21.00',
                'floors' => 5,
                'rooms_per_floor' => 'Lantai 1-5: Ruang Tamu, Kamar Asrama',
                'area' => 1500.0,
                'latitude' => -7.906390055353666,
                'longitude' => 112.57931469887176,
                'additional_facilities' => 'Wi-Fi gratis, Area parkir, Kasur dan Lemari',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/asrama.jpg',
            ],
            [
                'name' => 'Rumah Singgah',
                'address' => 'Jl. Raya Dadaprejo No.1, Dadaprejo, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Rumah Singgah adalah fasilitas yang disediakan oleh Pascasarjana UIN Maulana Malik Ibrahim Malang untuk memenuhi kebutuhan akomodasi mahasiswa dan dosen.',
                'opening_hours' => 'Senin - Minggu: 24 Jam',
                'floors' => 2,
                'rooms_per_floor' => 'Lantai 1-2: Kamar Penginapan',
                'area' => 1500.0,
                'latitude' => -7.906691592081385,
                'longitude' => 112.57939650624509,
                'additional_facilities' => 'Wi-Fi gratis, Area parkir, Tempat tidur dan lemari',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/rumahsinggah.jpg',
            ],
            [
                'name' => 'PSPD (Gedung Asrama Mahasiswa/i Pendidikan Dokter)',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'PSPD adalah fasilitas hunian yang disediakan khusus untuk mahasiswa dan mahasiswi jurusan Pendidikan Dokter.',
                'opening_hours' => 'Senin - Minggu: 04.00 - 21.00',
                'floors' => 5,
                'rooms_per_floor' => 'Lantai 1-5: Ruang Tamu, Kamar Asrama',
                'area' => 1500.0,
                'latitude' => -7.906824427574322,
                'longitude' => 112.5791416963937,
                'additional_facilities' => 'Wi-Fi gratis, Area parkir, Kasur dan Lemari',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/asrama1.jpg',
            ],
            [
                'name' => 'Masjid Muhammad Ali Shobuni',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Masjid Muhammad Ali Shobuni adalah pusat kegiatan ibadah dan keagamaan di UIN Maulana Malik Ibrahim Malang Kampus 2.',
                'opening_hours' => 'Senin - Minggu: 24 Jam',
                'floors' => 3,
                'rooms_per_floor' => 'Lantai 1: Ruang Pertemuan; Lantai 2-3: Tempat Ibadah, pengajian, dan kelas keagamaan',
                'area' => 1500.0,
                'latitude' => -7.906725664286216,
                'longitude' => 112.57862740428803,
                'additional_facilities' => 'Wi-Fi gratis, Area parkir, Mic',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/masjid.jpg',
            ],
            [
                'name' => 'Tempat Wudhu Masjid Muhammad Ali Shobuni',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Tempat Wudhu Masjid Muhammad Ali Shobuni adalah fasilitas yang dirancang khusus untuk jamaah yang ingin melaksanakan wudhu sebelum menjalankan ibadah sholat.',
                'opening_hours' => 'Senin - Minggu: 24 Jam',
                'floors' => 1,
                'rooms_per_floor' => 'Lantai 1: Tempat Wudhu',
                'area' => 100.0,
                'latitude' => -7.906666511688722,
                'longitude' => 112.57866802728206,
                'additional_facilities' => 'Wi-Fi gratis, Area parkir',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/wudhu.jpg',
            ],
            [
                'name' => 'Gudang',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Gudang adalah fasilitas yang berfungsi sebagai pusat penyimpanan barang untuk berbagai keperluan, baik untuk keperluan operasional harian maupun stok inventaris jangka panjang.',
                'opening_hours' => 'Senin - Jumat: 07.00 - 17.00, Sabtu - Minggu: Tutup',
                'floors' => 1,
                'rooms_per_floor' => 'Lantai 1: Tempat Penyimpanan',
                'area' => 1500.0,
                'latitude' => -7.906175724925858,
                'longitude' => 112.57856034905457,
                'additional_facilities' => 'Peralatan Kebersihan, dan sebagainya',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/gudang.jpg',
            ],
            [
                'name' => 'Gedung Asrama',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Gedung Asrama adalah fasilitas yang didalamnya terdapat resepsionis yang berfungsi sebagai pusat layanan, termasuk tempat penitipan barang dan makanan.',
                'opening_hours' => 'Senin - Minggu: 24 Jam',
                'floors' => 1,
                'rooms_per_floor' => 'Lantai 1: Tempat Penyimpanan',
                'area' => 1500.0,
                'latitude' => -7.906579545200482,
                'longitude' => 112.57904985220564,
                'additional_facilities' => 'Wi-Fi gratis, Rak dan lemari untuk penitipan barang dan makanan, Kamar Mandi',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/asrama.jpg',
            ],
            [
                'name' => 'Lapangan Badminton dan Gazebo',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Lapangan Badminton dan Gazebo adalah fasilitas olahraga yang disediakan untuk mendukung kegiatan olahraga dan rekreasi para mahasiswa dan staf.',
                'opening_hours' => 'Senin - Minggu: 07.00 - 17.00',
                'floors' => 1,
                'rooms_per_floor' => 'Lantai 1: Lapangan Badminton dan Gazebo',
                'area' => 1500.0,
                'latitude' => -7.906661903233506,
                'longitude' => 112.57931404980042,
                'additional_facilities' => 'Wi-Fi gratis',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/lapangan.jpg',
            ],
            [
                'name' => 'Parkiran',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Parkiran adalah area yang disediakan untuk parkir kendaraan bermotor. Dengan kapasitas yang lumayan luas, parkiran ini mampu menampung kendaraan roda dua maupun roda empat dari mahasiswa, dan staf.',
                'opening_hours' => 'Senin - Minggu: 24 Jam',
                'floors' => 1,
                'rooms_per_floor' => 'Lantai 1: Parkiran',
                'area' => 1500.0,
                'latitude' => -7.9065649332896815,
                'longitude' => 112.57888355524244,
                'additional_facilities' => 'Sekat pembatas antar kendaraan',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/parkiran.jpg',
            ],
            [
                'name' => 'Parkiran',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Parkiran adalah area yang disediakan untuk parkir kendaraan bermotor. Dengan kapasitas yang lumayan luas, parkiran ini mampu menampung kendaraan roda dua maupun roda empat dari mahasiswa, dan staf.',
                'opening_hours' => 'Senin - Minggu: 24 Jam',
                'floors' => 1,
                'rooms_per_floor' => 'Lantai 1: Parkiran',
                'area' => 1500.0,
                'latitude' => -7.906190336852637,
                'longitude' => 112.5793422129827,
                'additional_facilities' => 'Sekat pembatas antar kendaraan',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/parkiran.jpg',
            ],
            [
                'name' => 'Parkiran',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Parkiran adalah area yang disediakan untuk parkir kendaraan bermotor. Dengan kapasitas yang lumayan luas, parkiran ini mampu menampung kendaraan roda dua maupun roda empat dari mahasiswa, dan staf.',
                'opening_hours' => 'Senin - Minggu: 24 Jam',
                'floors' => 1,
                'rooms_per_floor' => 'Lantai 1: Parkiran',
                'area' => 1500.0,
                'latitude' => -7.906547664668579,
                'longitude' => 112.57833236128107,
                'additional_facilities' => 'Sekat pembatas antar kendaraan',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/parkiran.jpg',
            ],
            [
                'name' => 'Parkiran',
                'address' => 'Jl. Raya Dadaprejo No.143, Pendem, Kec. Junrejo, Kota Batu, Jawa Timur 65233',
                'description' => 'Parkiran adalah area yang disediakan untuk parkir kendaraan bermotor. Dengan kapasitas yang lumayan luas, parkiran ini mampu menampung kendaraan roda dua maupun roda empat dari mahasiswa, dan staf.',
                'opening_hours' => 'Senin - Minggu: 24 Jam',
                'floors' => 1,
                'rooms_per_floor' => 'Lantai 1: Parkiran',
                'area' => 1500.0,
                'latitude' => -7.906167754782177,
                'longitude' => 112.57788845569335,
                'additional_facilities' => 'Sekat pembatas antar kendaraan',
                'contact_info' => 'Telp: +62-341 531-133, Email: pps@uin-malang.ac.id',
                'image_path' => 'home_assets/img/parkiran.jpg',
            ],
        ]);
    }
}
